### ISSUE TITLE
If always-auth is set to true, then public packages will fail

### ISSUE THREAD

**Issue by ekristen** [npm/npme-auth-github#8]
It appears that if always-auth is set to true, then pulling public packages will fail with an auth failure.

**Comment by bcoe** [comment]
Hey @ekristen, is this still giving you trouble -- once you've logged in to your npm Enterprise appliance I think it's probably best to avoid setting `always-auth`.

The token will be automatically kicked along during requests.

**Comment by bcoe** [comment]
This should now be fixed in newer version of npm On-Site, please feel free to reopen this if you continue to run into problems.
